### ISSUE TITLE
[Anon] Bug report: Brotherhood.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warzone-resurrection#37]
**File:** Brotherhood.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Taking captain mitch hunter as a doomtrooper dosent add the sea lions as troop choices to the brotherhood list. As per his ability there are no restrictions unlike all the other doomtroopers. This was actually an intentional design choice as he was one of the primary points of discussion that led to the restriction being added to the rest of the doom troopers.

**Comment by SpecialAgent45954** [comment]
I asked on the Warzone FB group, and no one remembers this detail. If you have any source, please, share, otherwise I will consider it as not a defect, because I cannot find anything specific in the manual specifying so.

**Comment by SpecialAgent45954** [comment]
Closing as Invalid
