### ISSUE TITLE
[Anon] Bug report: Imperial-_Ministries_of_War.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warzone-resurrection#4]
**File:** Imperial-_Ministries_of_War.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** This position doesn't appear + some minimalist bugs in other fractions like coherency 209 in some units

**Comment by SpecialAgent45954** [comment]
Fixed with Release 2.3.18
