### ISSUE TITLE
Error: At Line 9160 Column 484: reference to invalid character number

### ISSUE THREAD

**Issue by bruno-cyberpunk** [BSData/warzone-resurrection#5]
**Error:** At Line 9160 Column 484: reference to invalid character number.
**BattleScribe version:** 2.03.22.333
**Platform:** Android
Also Capitol is showing as V1, and some troops aren't being showed(Not only for Capitol). This Error occurs when you try to update the file or download it for the first time from BattleScribe Repository. 
I know the game is "dead" but it would be nice to have a platform to create rosters for armies.

**Comment by SpecialAgent45954** [comment]
Fixed with Release 2.3.18
