### ISSUE TITLE
[Anon] Bug report: Imperial-_Ministries_of_War.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warzone-resurrection#6]
**File:** Imperial-_Ministries_of_War.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** No

**Description:** I can See an error: "At line 9160, column 484: referencje to invalid character number" pls help!

**Comment by SpecialAgent45954** [comment]
Fixed with Release 2.3.18
