### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by SpecialAgent45954** [BSData/warzone-resurrection#7]
### Reference contact

@amis92

### Your Discord

SpecialAgent45954

### Additional information

Hello, please, enable me to provide update to Warzone Resurrection game. I am member on all the Facebook groups of the game and we continue to play here in Italy. There are some bug fixes to be done, and new armies to be included, as they are created by the international fan base. I need to learn how these files are created, but I will normally test them and let my friends test them before committing them.

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/1560266748)
:robot: Invited @SpecialAgent45954 with **push** access. Invite can be accepted on https://github.com/BSData/warzone-resurrection/invitations
